name: ML Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:

    # -------------------------------
    # STEP 1: Checkout repo
    # -------------------------------
    - name: Checkout repository
      uses: actions/checkout@v3


    # -------------------------------
    # STEP 2: Setup Python
    # -------------------------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"


    # -------------------------------
    # STEP 3: Install dependencies
    # -------------------------------
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt


    # -------------------------------
    # STEP 4: Run pipeline
    # -------------------------------
    - name: Run ML pipeline
      run: python pipeline/run_pipeline.py


    # -------------------------------
    # STEP 5: Upload models (IMPORTANT)
    # -------------------------------
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: final-model
        path: models/


    # -------------------------------
    # STEP 6: Upload logs (optional)
    # -------------------------------
    - name: Upload logs (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: |
          *.log
